### ISSUE TITLE
Leader Board Bug

### ISSUE THREAD

**Issue by EmojiPati** [Tomato6966/discord-leveling-system-ranking-system#2]
Some people's names do not appear in the Leaderboards, and their ranking is incorrect
For example, it should be listed as 1-2-3, but it is listed as 1-3-5-8-9

![image](https://user-images.githubusercontent.com/49492351/100712716-40e09a00-33c4-11eb-835f-78a6162e9d34.png)

**Comment by Tomato6966** [comment]
Hmmmmm and u use my code?
