### ISSUE TITLE
How to make the bot.points go to a database like quick.db or something

### ISSUE THREAD

**Issue by Aayush-683** [Tomato6966/discord-leveling-system-ranking-system#4]
can i set bot.points using a database? like if i can do db.set(bot.points) something or put it to a database in general :P

**Comment by Aayush-683** [comment]
i wanna do this cus im self hosting this repo on repl.it and there is dataloss 🤕

**Comment by Tomato6966** [comment]
client.points is already a database... [enmap.evie.dev/api](https://enmap.evie.dev/api)
