### ISSUE TITLE
Leaderboard undefined bug

### ISSUE THREAD

**Issue by Aayush-683** [Tomato6966/discord-leveling-system-ranking-system#5]
When a user talks, he is given some points in the database and added to the lederboard, but when he leaves the server, his points still stay in the leaderboard but name changes to undefined :/
![image](https://user-images.githubusercontent.com/75422863/114815699-0ac21680-9db7-11eb-9bd2-62a27f986fa8.png)
 anyway how to fix that / delete the user's points as soon as he leaves the server?

**Comment by Aayush-683** [comment]
@Tomato6966

**Comment by Aayush-683** [comment]
I Have tried adding this but doesn't seem to function...
```js
bot.on('guildMemberLeave', async (member) => {
    bot.points.delete(`${member.guild.id}-${member.user.id}`)
  })
```

**Comment by ClaraCrazy** [comment]
dead project

**Comment by Tomato6966** [comment]
@BlackKnight683 if you know discord.js client events you just should do:
```js
bot.on('guildMemberRemove', (member) => {
    bot.points.delete(`${member.guild.id}-${member.user.id}`)
  }) 
```
as your given Event is not existing, and sorry for not answering ... i didnt got notified

**Comment by ClaraCrazy** [comment]
Well.. apparently not a dead project. my apologies
